### ISSUE TITLE
Error: Could not find function "pdist"

### ISSUE THREAD

**Issue by mloning** [BigBayes/kernelpoisson#1]
I try to familiarise myself with your RKHS methods for estimating the intensity using your paper and R script. After installing the required packages, when running `gaussian-mixture-synthetic-experiment.r`, I get the following error:
```
Error in { : 
  task 1 failed - "task 1 failed - "could not find function "pdist"""
```
Could you please specify the R and package versions that you use?

**Comment by mloning** [comment]
Seems to be a Windows-related issue. When running it on a Linux server, it works without any problems.

**Comment by flaxter** [comment]
Yeah, there's some issues with the various R parallelization packages and loading libraries which I don't understand. pdist comes from the pdist library, you can try putting library(pdist) at the top of any function that uses it. Another fix to try: if you need to use Windows, maybe switch doMC to doParallel (or one of the others that provides the same functionality) and see if it works. Or of course, just stick with Linux when you need parallelization. I think Windows will work if you switch from %dopar% (parallel computation) to %do% (serial computation).

**Comment by mloning** [comment]
Thanks for your suggestions! I'll try them out. This basically solves my issue.
